### PR TITLE
Update bool datatype tests

### PR DESCRIPTION
**Pull request by DonAurelio**
* We updated the bool data type test.
* It validates correct geneartion of the type in source and filter.
* It validates consistency and correctness of values through the state machine.

### CODE REVIEW

**Comment by DonAurelio** [comment]
I think we are good to go.

**Comment by DonAurelio** [comment]
Good to go?

**Comment by TApplencourt** [comment]
why we need test detail there?

**Comment by DonAurelio** [comment]
You are right, we do not need it, i just tried to keep the same test structute for the data_type tests. I just updated it.

**Pull request merged**
